apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow
        image: apache/airflow:2.1.0
        ports:
        - containerPort: 8080
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: sqlite:////usr/local/airflow/airflow.db
        - name: AIRFLOW__CORE__FERNET_KEY
          value: "your_fernet_key"
        volumeMounts:
        - name: airflow-logs
          mountPath: /usr/local/airflow/logs
      volumes:
      - name: airflow-logs
        emptyDir: {}

